Repository macnev2013/gh-action-services-test, pull requests merged in 2022-04, with the labels that each got.

#1 updated readme
  README.md
Labels: release:patch

#2 commit from forked repo
  README.md
Labels: release:patch

#3 updated GH_TOKEN
  README.md
Labels: release:patch

#4 Permission in actions
  README.md
Labels: release:patch

#5 addded admin token
  README.md
Labels: release:patch

#7 Update README.md
  README.md
Labels: release:patch

#9 Update README.md
  README.md
Labels: release:patch

#10 Update README.md
  README.md
Labels: release:patch

#12 Update README.md
  README.md
Labels: release:patch

#13 Update release.yml
  .github/workflows/release.yml
Labels: release:patch

#14 Update README.md
  README.md
Labels: release:patch

#15 opensource
  README.md
Labels: release:patch

#17 Update release.yml
  .github/workflows/release.yml
Labels: release:patch

#18 Update README.md
  README.md
Labels: release:patch

#19 Update README.md
  README.md
Labels: release:patch

#22 Update README.md
  README.md
Labels: release:patch

#24 Update push.yml
  .github/workflows/push.yml
Labels: release:patch

#25 Update release.yml
  .github/workflows/release.yml
Labels: release:minor

#26 Update README.md
  README.md
Labels: release:major

#27 fork test
  README.md
Labels: release:minor

#28 Update README.md
  README.md
Labels: release:major

#31 Update README.md
  README.md
Labels: release:major

#32 Update README.md
  README.md
Labels: bug, release:patch

#33 Create pr-lint.yml
  .github/workflows/pr-lint.yml
Labels: release:major

#34 Update README.md
  README.md
Labels: release:major
